name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: gift-card-wallet.myshopify.com
          password: gift
          access_token: shpua_9c242ad5fab328d55fdd03a59d0617c7
          lhci_min_score_performance: 0.1
          lhci_min_score_accessibility: 0.1